[package]
name = "unit-fractions"
version = "0.1"
lean_version = "leanprover-community/lean:3.40.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "115f8c7ab221914bc38d7abaa327aefc980127a0"}
